apiVersion: v1
kind: Service
metadata:
  name: member-db
spec:
  ports:
    - port: 3306
  selector:
    app: member-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-db
spec:
  selector:
    matchLabels:
      app: member-db
  template:
    metadata:
      labels:
        app: member-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: Never
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: library-secrets
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: "member_db"
            - name: MYSQL_USER
              value: "library_user"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: library-secrets
                  key: mysql-user-password
          ports:
            - containerPort: 3306