apiVersion: v1
kind: Service
metadata:
  name: member-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: member-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-service
  template:
    metadata:
      labels:
        app: member-service
    spec:
      containers:
        - name: member-service
          image: member-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: DB_HOST
              value: "member-db"
            - name: DB_USERNAME
              value: "library_user"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: library-secrets
                  key: mysql-user-password
            - name: REDIS_HOST
              value: "redis"
            - name: APP_BASE_URL
              value: "http://localhost:8080"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: library-secrets
                  key: google-client-id
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: library-secrets
                  key: google-client-secret
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI
              value: "http://localhost:8080/login/oauth2/code/google"