apiVersion: v1
kind: Secret
metadata:
  name: library-secrets
type: Opaque
stringData:
  # Database Credentials
  mysql-root-password: "YOUR_ROOT_PASSWORD_HERE"
  mysql-user-password: "YOUR_DB_PASSWORD_HERE"

  # Google OAuth2 Credentials
  google-client-id: "YOUR_GOOGLE_CLIENT_ID_HERE"
  google-client-secret: "YOUR_GOOGLE_CLIENT_SECRET_HERE"